language: php

sudo: false

php:
  - 5.3
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: deps="low" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 5.6
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" != "low" ]; then composer update --prefer-source; fi

script:
  - phpunit --coverage-text --colors
  - Tests/Javascript/runner.py Tests/Javascript/test.html
