language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  
cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.1.*'

install: php -d memory_limit=-1 composer update $COMPOSER_FLAGS --prefer-dist

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

script:
  - phpunit --coverage-text --colors
  - Tests/Javascript/runner.py Tests/Javascript/test.html
